### ISSUE TITLE
Video Not starting on Android 13

### ISSUE THREAD

**Issue by Dhawansumit** [flutterwtf/VR-Player#40]
Working in android 11
Getting below error in android 13: 

W/MediaCodecRenderer(20801): Failed to initialize decoder: c2.mtk.avc.decoder
W/MediaCodecRenderer(20801):   java.lang.IllegalArgumentException
W/MediaCodecRenderer(20801):       at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(20801):       at android.media.MediaCodec.configure(MediaCodec.java:2214)
W/MediaCodecRenderer(20801):       at android.media.MediaCodec.configure(MediaCodec.java:2130)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1090)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1001)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:536)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1444)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:945)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:760)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
W/MediaCodecRenderer(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
W/MediaCodecRenderer(20801):       at android.os.Handler.dispatchMessage(Handler.java:102)
W/MediaCodecRenderer(20801):       at android.os.Looper.loopOnce(Looper.java:211)
W/MediaCodecRenderer(20801):       at android.os.Looper.loop(Looper.java:300)
W/MediaCodecRenderer(20801):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(20801): Video codec error
E/MediaCodecVideoRenderer(20801):   com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder, Format(0, null, null, video/avc, avc1.640033, -1, null, [4096, 2048, -1.0], [-1, -1])
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1012)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:536)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1444)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:945)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:760)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
E/MediaCodecVideoRenderer(20801):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer(20801):       at android.os.Looper.loopOnce(Looper.java:211)
E/MediaCodecVideoRenderer(20801):       at android.os.Looper.loop(Looper.java:300)
E/MediaCodecVideoRenderer(20801):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(20801):   Caused by: java.lang.IllegalArgumentException
E/MediaCodecVideoRenderer(20801):       at android.media.MediaCodec.native_configure(Native Method)
E/MediaCodecVideoRenderer(20801):       at android.media.MediaCodec.configure(MediaCodec.java:2214)
E/MediaCodecVideoRenderer(20801):       at android.media.MediaCodec.configure(MediaCodec.java:2130)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1090)
E/MediaCodecVideoRenderer(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1001)
E/MediaCodecVideoRenderer(20801):       ... 11 more
D/MediaCodecInfo(20801): NoSupport [sizeAndRate.cover, 4096x2048@-1.0] [c2.mtk.avc.decoder, video/avc] [miel, 2201117PI, Xiaomi, 33]
D/MediaCodecInfo(20801): NoSupport [sizeAndRate.support, 4096x2048@-1.0] [c2.android.avc.decoder, video/avc] [miel, 2201117PI, Xiaomi, 33]
E/ExoPlayerImplInternal(20801): Playback error
E/ExoPlayerImplInternal(20801):   com.kaltura.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.640033, -1, null, [4096, 2048, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
E/ExoPlayerImplInternal(20801):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(20801):       at android.os.Looper.loopOnce(Looper.java:211)
E/ExoPlayerImplInternal(20801):       at android.os.Looper.loop(Looper.java:300)
E/ExoPlayerImplInternal(20801):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(20801):   Caused by: com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder, Format(0, null, null, video/avc, avc1.640033, -1, null, [4096, 2048, -1.0], [-1, -1])
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1012)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:536)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1444)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:945)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:760)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
E/ExoPlayerImplInternal(20801):       ... 4 more
E/ExoPlayerImplInternal(20801):   Caused by: java.lang.IllegalArgumentException
E/ExoPlayerImplInternal(20801):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(20801):       at android.media.MediaCodec.configure(MediaCodec.java:2214)
E/ExoPlayerImplInternal(20801):       at android.media.MediaCodec.configure(MediaCodec.java:2130)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1090)
E/ExoPlayerImplInternal(20801):       at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1001)
E/ExoPlayerImplInternal(20801):       ... 11 more
D/BufferQueueConsumer(20801): [SurfaceTexture-1-20801-3](id:514100000009,api:0,p:-1,c:20801) disconnect
D/libMEOW (20801): meow delete tls: 0xb4000077ce465840
D/ExoPlayerWrapper(20801): onPlayerError error type => 4001
E/PKPlaybackException(20801): Unable to instantiate decoderc2.mtk.avc.decoder
E/ExoPlayerWrapper(20801): ExoPlaybackException, type = RENDERER_ERROR

**Comment by Crow-Eater** [comment]
I tried to start the video on real device with android 13 and everything was okay. Check one more time versions of kotlin, agp, java and other android things in your project
